import fs from "fs/promises";
import path from "path";
import matter from "gray-matter";
import type { CourseMeta, Lesson, LessonFrontmatter, TestCase } from "../lib/learn/types";

// Bake the contents of content/learn/ into a generated TS module so the rest
// of the app can read lessons without ever touching the filesystem at runtime.
// The Cloudflare worker bundle does not have a usable cwd / fs view, so any
// fs.* call from a server component returns nothing, which is what was making
// /learn show "No courses yet" in production even though the markdown was
// committed and visible during local builds.

const CONTENT_ROOT = path.join(process.cwd(), "content", "learn");
const OUT_FILE = path.join(process.cwd(), "lib", "learn", "generated.ts");

interface GeneratedCourse {
  meta: CourseMeta;
  lessons: Lesson[];
}

async function listCourseSlugs(): Promise<string[]> {
  const dirents = await fs.readdir(CONTENT_ROOT, { withFileTypes: true });
  return dirents.filter((d) => d.isDirectory()).map((d) => d.name);
}

async function readJson<T>(filePath: string): Promise<T> {
  const raw = await fs.readFile(filePath, "utf8");
  return JSON.parse(raw) as T;
}

async function readLesson(courseSlug: string, lessonDir: string): Promise<Lesson> {
  const dirPath = path.join(CONTENT_ROOT, courseSlug, lessonDir);
  const indexPath = path.join(dirPath, "index.md");
  const raw = await fs.readFile(indexPath, "utf8");
  const parsed = matter(raw);
  const data = parsed.data as Partial<LessonFrontmatter> | undefined;
  if (!data?.slug || !data?.title || typeof data?.order !== "number" || !data?.exercise) {
    throw new Error(`invalid frontmatter at ${indexPath}`);
  }
  const frontmatter: LessonFrontmatter = {
    slug: data.slug,
    title: data.title,
    description: data.description,
    order: data.order,
    exercise: { prompt: data.exercise.prompt ?? "" },
  };
  const [starter, solution, tests] = await Promise.all([
    fs.readFile(path.join(dirPath, "starter.cpp"), "utf8"),
    fs.readFile(path.join(dirPath, "solution.cpp"), "utf8"),
    readJson<TestCase[]>(path.join(dirPath, "tests.json")),
  ]);
  return {
    courseSlug,
    slug: frontmatter.slug,
    title: frontmatter.title,
    description: frontmatter.description,
    order: frontmatter.order,
    body: parsed.content,
    exercise: frontmatter.exercise,
    starter,
    solution,
    tests,
  };
}

async function buildCourse(slug: string): Promise<GeneratedCourse | null> {
  let meta: CourseMeta;
  try {
    meta = await readJson<CourseMeta>(path.join(CONTENT_ROOT, slug, "course.json"));
  } catch {
    return null;
  }
  const lessons: Lesson[] = [];
  for (const lessonDir of meta.lessons) {
    try {
      lessons.push(await readLesson(slug, lessonDir));
    } catch (err) {
      console.warn(`Skipping ${slug}/${lessonDir}: ${(err as Error).message}`);
    }
  }
  lessons.sort((a, b) => a.order - b.order);
  return { meta, lessons };
}

async function main() {
  let slugs: string[];
  try {
    slugs = await listCourseSlugs();
  } catch {
    slugs = [];
  }
  const courses: GeneratedCourse[] = [];
  for (const slug of slugs) {
    const course = await buildCourse(slug);
    if (course) courses.push(course);
  }
  courses.sort((a, b) => a.meta.order - b.meta.order);

  const banner =
    "// AUTO-GENERATED by scripts/build-learn.ts. Do not edit by hand.\n" +
    "// Run `pnpm run prebuild` (or `tsx scripts/build-learn.ts`) to refresh.\n\n";
  const body =
    `import type { GeneratedCourse } from "./generated-types";\n\n` +
    `export const LEARN_COURSES: GeneratedCourse[] = ${JSON.stringify(courses, null, 2)};\n`;

  await fs.writeFile(OUT_FILE, banner + body, "utf8");
  const totalLessons = courses.reduce((acc, c) => acc + c.lessons.length, 0);
  console.log(
    `Wrote ${courses.length} course(s) and ${totalLessons} lesson(s) to ${path.relative(
      process.cwd(),
      OUT_FILE
    )}`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
